version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    environment:
      - ENV = "linux"
networks:
  default:
     # Use a custom driver
     external:
      name: isolated_network
